name: Build and Publish Docker Image

on:
  push:
    branches:
      - master
  pull:
    branches:
      - master    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build and push Docker image
      run: |
        docker build -t autom8ers/CA3:latest .
        echo Salis2002$ | docker login -u autom8ers --password-stdin
        docker push autom8ers/CA3:latest